### ISSUE TITLE
Implement task management pages (my tasks, open tasks and all tasks)

### ISSUE THREAD

**Issue by ruppfabian1997** [remsfal/remsfal-frontend#107]
The task management page is used to record and manage various project tasks. The tasks are categorized as “my tasks”, “open tasks” and “all tasks”. The categories can be found in the individual menu items of the project overview.

**Comment by ruppfabian1997** [comment]
I would like to work on this as my KBA issue

**Comment by astanik** [comment]
This issue is based on https://github.com/remsfal/remsfal-backend/issues/134

**Comment by astanik** [comment]
@ruppfabian1997 The backend functionality is implemented with [remsfal/remsfal-backend#157](https://github.com/remsfal/remsfal-backend/pull/157)
