### ISSUE TITLE
Adding "Startseite" to the legal notice and privacy

### ISSUE THREAD

**Issue by Melodycel** [remsfal/remsfal-frontend#120]
When opening the legal notice or the privacy there is no chance to go back to the landing page. 
This could be done for example by:
- adding "Startseite" to the footer bevor "Impressum" and "Datenschutz" 
- clicking on the logo 
- adding a "Zurück" button

**Comment by astanik** [comment]
I agree. There should be a link named "< Zurück zur Startseite" at the top between the top bar and the first card.

**Comment by s0571584** [comment]
I want to do this one
