### ISSUE TITLE
Create property view in project dashboard

### ISSUE THREAD

**Issue by mzudse** [remsfal/remsfal-frontend#137]
Create a view in the project dashboard for properties.

- List all properties
- Create property
- Details for single property
- Delete property
- Update property

**Comment by HassanAlhawari1998** [comment]
The backend currently lacks specific API endpoints to fetch all types of object data(properties, sites, buildings, apartments, garages) individually or in a single request with the projectId

**Comment by HassanAlhawari1998** [comment]
close with #147
