### ISSUE TITLE
Make Logo navigate to Home

### ISSUE THREAD

**Issue by ChristopherDKeller** [remsfal/remsfal-frontend#203]
When the Logo is clicked (top left corner) the page should navigate to the root page. I find it unintuative that there is no way back to the landing page.

**Comment by astanik** [comment]
@ChristopherDKeller The landing page should only be viewable if the user is visiting the application on the root path and the user is not logged in. There is no other reason to navigate back to the landing page, unless you can give me a good reason.

If the user is logged in and no project is selected, the user should be on the project selection page.
If the user is logged in and a project is already selected, the user should be on the project dashboard.
