### ISSUE TITLE
Create initial test case for views/ProjectSettings.vue

### ISSUE THREAD

**Issue by Hannesson1** [remsfal/remsfal-frontend#207]
Testcase if correct ID is displayed and returned on setting page.

**Comment by astanik** [comment]
The tast case should be implemented in /test/views/ProjectSettings.spec.ts.

A good example of an initial test case can be found in /test/views/TaskView.spec.ts.

**Comment by Abdurrahmanhtw** [comment]
Ich würde das gerne übernehmen

**Comment by Abdurrahmanhtw** [comment]
Alles klar.

**Comment by Hannesson1** [comment]
#256 resolve this
