### ISSUE TITLE
Set cursor to pointer when hover over the logo

### ISSUE THREAD

**Issue by AliceKitchkin** [remsfal/remsfal-frontend#208]
Set cursor to pointer when hover over the logo

**Comment by AliceKitchkin** [comment]
claimed by me

**Comment by astanik** [comment]
I agree that this is a nice feature for the project presentation page at https://remsfal.de/ and will be implemented with issue https://github.com/remsfal/remsfal.github.io/issues/32. However, for reasons of user-friendliness, this behavior should not be implemented in the frontend application.
