### ISSUE TITLE
Replace Technical IDs in UI with Project Name or Relevant Labels

### ISSUE THREAD

**Issue by ZieglerAaron** [remsfal/remsfal-frontend#229]
**Description** 
Currently, the UI displays technical IDs in various parts of the application, which can be confusing for end-users. Replacing these IDs with the project name or other contextually relevant labels would improve user experience by making the interface more intuitive and user-friendly.
**Goal**
Update the UI to remove technical IDs in the views/ProjectSelectionView.vue and exchange the wording of 'Projekt' with 'Liegenschaft'.
**Proposed Solution**
- [x] Update the code to remove the ID.
- [x] Exchange occurrences of 'Projekt' with 'Liegenschaft'

**Comment by ZieglerAaron** [comment]
Hello @astanik, I'd like to implement this as a good first issue.

**Comment by astanik** [comment]
@ZieglerAaron A very good description and idea! However, most of the parts where technical IDs are displayed are under development. Therefore, I would suggest to focus in this issue on the projectID that is mainly depicted in views/ProjectSelectionView.vue

Another inconsistency is the german translation of a project that can be addressed with this issue. A project in this context is a "Liegenschaft" in german. For more details see https://remsfal.de/faq
