### ISSUE TITLE
Fix typo on the landingpage

### ISSUE THREAD

**Issue by ArniBananii** [remsfal/remsfal-frontend#276]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

## Task:
Fix the typo on the [landing page.](https://remsfal.de/)

<img width="886" alt="Screenshot 2024-11-19 at 22 38 27" src="https://github.com/user-attachments/assets/a08aa894-4903-4510-83be-ddc0eaea51b5">

## Acceptance criteria:
The text says: 
Remote Management Services for Connected Facilities

### Regression

- [ ] The issue is a regression

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

**Comment by astanik** [comment]
@ArniBananii Could you please be a little more precise. Where is the typo?

**Comment by ArniBananii** [comment]
Ticket closed due to misunderstanding. Will be translated into different issue.
