### ISSUE TITLE
Add vue Devtools 

### ISSUE THREAD

**Issue by ruppfabian1997** [remsfal/remsfal-frontend#72]
Implementing Vue Devtools is beneficial because it provides developers with real-time insights into the Vue.js application's component structure, state, and performance, facilitating efficient debugging and optimization processes. Additionally, Vue Devtools offers a seamless integration with Vue.js projects, empowering developers to visually inspect and manipulate component data flow, aiding in the development of robust and maintainable Vue.js applications

https://devtools.vuejs.org/

**Comment by FelixSiegfriedRiedel** [comment]
Good Idea, I will make a pull request for it!

**Comment by FelixSiegfriedRiedel** [comment]
Will be added in #88. Pull-Request is waiting for approval.
