### ISSUE TITLE
Sign in with google should open a new window

### ISSUE THREAD

**Issue by Tobiwue** [remsfal/remsfal-frontend#74]
At the moment, the “Sign in with Google” or “Sign in” button will take you to a new page.
A new window for login should be opened for quality of life improvements.
One reason for this could be that if someone clicked the wrong button, they don't have to reload the homepage and can simply close the "Sign In" window.

**Comment by astanik** [comment]
@Tobiwue Can you please create a real discussion as showcase for our next lecture?

<img width="1584" alt="Bildschirmfoto 2024-05-25 um 11 08 22" src="https://github.com/remsfal/remsfal-frontend/assets/7569599/a215b26c-08b8-4b74-83c5-3f5be6f7ff91">

**Comment by Tobiwue** [comment]
Sure. I try to create a discussion about this topic.

**Comment by astanik** [comment]
This need to be discussed in #80
