### ISSUE TITLE
Implement the landing page

### ISSUE THREAD

**Issue by Melodycel** [remsfal/remsfal-frontend#75]
Adding an welcoming start page to inform the users about the function of the program. Maybe include screenshots, list the benefits and current state of the program.

**Comment by astanik** [comment]
This issue relates to https://github.com/remsfal/remsfal-frontend/blob/main/src/views/LandingPageView.vue

**Comment by Melodycel** [comment]
I created three mockups for the landing page as first drafts. They only include some information mentioned on the Remsfal website. Since there are no complete pages of the project, it would not make sense to show screenshots of the application for now.

I would appreciate any feedback on the mockups. What could be changed or added to the page to enhance it? 
Please note that these are mockups, and they might look different when implemented with code.

<img width="1440" alt="Mockup1" src="https://github.com/remsfal/remsfal-frontend/assets/166515998/d6d706b2-389f-4359-bf63-3b7758889764">
<img width="1440" alt="Mockup2" src="https://github.com/remsfal/remsfal-frontend/assets/166515998/0234131d-e87e-4828-ae24-01ad611616c0">
<img width="1440" alt="Mockup3" src="https://github.com/remsfal/remsfal-frontend/assets/166515998/6acbca91-cf06-48cd-9918-065ef351e304">

**Comment by astanik** [comment]
Nice mockups! I like the third one.

Can you please add the following text as some kind of footnote: "Mit der Anmeldung stimmen Sie den Nutzungs- und Datenschutzbedingungen zu."

And I would use the google button ("Mit Google anmelden"), because it tells the user what happens next. Otherwise the user might be confused.
