### ISSUE TITLE
Wrong landing page after login

### ISSUE THREAD

**Issue by astanik** [remsfal/remsfal-frontend#93]
After logging in, the [select project page](https://github.com/remsfal/remsfal-frontend/blob/main/src/views/ProjectSelectionView.vue) should be displayed

**Comment by astanik** [comment]
If the user only has one project, that project should be selected as the default and the project dashboard should be displayed.

**Comment by astanik** [comment]
@FelixSiegfriedRiedel: If I remember correctly, you also wanted to address this behavior as part of your KBA issue? Correct?

**Comment by FelixSiegfriedRiedel** [comment]
@astanik Yes! This is already featured in my latest draft. #121

**Comment by FelixSiegfriedRiedel** [comment]
This can be closed. 
Now a `route` can be passed to the login function to configure the redirect. 

```
login(route: string): void {
   window.location.href = `/api/v1/authentication/login?route=${encodeURIComponent(route)}`;
}
```
`<button class="gsi-material-button" @click="login('/projects')">`
