### ISSUE TITLE
Implement project selection page

### ISSUE THREAD

**Issue by astanik** [remsfal/remsfal-frontend#94]
This issue relates to https://github.com/remsfal/remsfal-frontend/blob/main/src/views/ProjectSelectionView.vue

This page is displayed after login, if no project exists or no project is selected in the topbar.

Minimum requirements for this issue:
- The user receives an overview of the projects
- The user can create a new project
- The user can select a project that will also be changed in the topbar

**Comment by FelixSiegfriedRiedel** [comment]
Great idea! I would like to work on that :)

**Comment by FelixSiegfriedRiedel** [comment]
![grafik](https://github.com/remsfal/remsfal-frontend/assets/61734168/49066011-84bd-4866-ac75-3fa68b7c1d4a)

I would implement it like that, using a Sakai table with clickable rows that lead to the respective project page.
