### ISSUE TITLE
Add stylelint

### ISSUE THREAD

**Issue by Melodycel** [remsfal/remsfal-frontend#98]
Adding stylelint to identify errors and establish structure in CSS and Vue code.
The package.json file should be extended with stylelint under the scripts section. Additionally, the rules should be customized for the project and the command for execution should be added to the README.

Later it should be integrated in the pipeline.

**Comment by Melodycel** [comment]
I would like to implement this issue.

**Comment by astanik** [comment]
Please also note the scss styling, e.g. https://github.com/remsfal/remsfal-frontend/blob/main/src/assets/styles.scss or https://github.com/remsfal/remsfal-frontend/blob/cb1c6e447a4ef250374fdef8f20859c697fb09ed/src/layout/AppTopbar.vue#L129
